cap/cap/urls.py
import os

from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from django.views.static import serve

urlpatterns = [
    path("", include('prcr.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon
urlpatterns += [
    path('favicon.ico', serve, {
        'path': 'favicon.ico',
        'document_root': os.path.join(BASE_DIR, 'home/static')
    }),
]

# Switch to social login if it is configured
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

cap/prcr/urls.py
from django.urls import path
from . import views

app_name = 'prcr'
urlpatterns = [
    # Category list view
    path('', views.CategoryListView.as_view(), name='main_list'),

    # Category and subcategory create views
    path('new_category', views.CategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/new_subcategory',
         views.SubcategoryCreateView.as_view(), name='subcategory_create'),

    # Brand create view
    path('new_brand', views.BrandCreateView.as_view(), name='brand_create'),

    # Brand list view
    path('brands', views.BrandListView.as_view(), name='brand_list'),
    # Create product from brand list view
    path('brands/<int:pk>/create_product',
         views.ProductBrandCreateView.as_view(), name='product_brand_create'),

    # Product list view
    path('subcategory/<int:pk>/products', views.ProductListView.as_view(), name='product_list'),
    # Create product from subcategory list view
    path('subcategory/<int:pk>/create_product',
         views.ProductSubcategoryCreateView.as_view(), name='product_subcategory_create'),

    # Product detail, update and add image views
    path('products/<int:pk>/detail', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<int:pk>/update', views.ProductUpdateView.as_view(), name='product_update'),
    path('products/<int:pk>/add_image', views.ProductAddImageView.as_view(), name='product_add_image'),

    # Feature create view
    path('product/<int:pk>/new_feature', views.FeatureCreateView.as_view(), name='feature_create'),

    # Price create & update view
    path('product/<int:pk>/new_price', views.PriceCreateView.as_view(), name='price_create'),
    path('update_price/<int:pk>', views.PriceUpdateView.as_view(), name='price_update'),

    # Product picture view
    path('picture/<int:pk>', views.stream_file, name='product_picture'),

    # Comment create and delete views
    path('product/<int:pk>/comment', views.CommentCreateView.as_view(), name='comment_create'),
    path('comment/<int:pk>/delete',  views.CommentDeleteView.as_view(), name='comment_delete'),

    path('comment/<int:pk>/like', views.LikeCommentView.as_view(), name='like_comment'),
    path('comment/<int:pk>/dismiss_like', views.DismissLikeView.as_view(), name='dismiss_like'),
]

cap/prcr/models.py
from django.db import models
from django.core.validators import MinLengthValidator, MinValueValidator
# from django.contrib.auth.models import User
from django.conf import settings

from decimal import Decimal

# from taggit.managers import TaggableManageer # need to install and add to settings

class Category(models.Model):
    category = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Category name must be longer than two letters.")],
        unique=True,
    )
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.category

    class Meta:
        verbose_name_plural = "categories"


class SubCategory(models.Model):
    subcategory = models.CharField(
        max_length=50,
        validators=[MinLengthValidator(2, "Sub-category name must be longer than two letters.")],
        unique=True,
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE,
        related_name="subcategory_category")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.subcategory

    class Meta:
        verbose_name = "subcategory"
        verbose_name_plural = "subcategories"


class Brand(models.Model):
    brand = models.CharField(
        max_length=128,
        validators=[MinLengthValidator(2, "Brand name must be longer than two letters.")],
        unique=True,
    )
    company = models.CharField(
        max_length=128,
        validators=[MinLengthValidator(2, "Brand name must be longer than two letters.")]
    )
    class Meta:
        unique_together = ['brand', 'company']

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        if self.company:
            return self.brand + " (" + self.company + ")"
        else:
            return self.brand


class Product(models.Model):
    product = models.CharField(
        max_length=128,
        validators=[MinLengthValidator(2, "Product name must be longer than two letters.")],
        unique=True,
    )
    brand = models.ForeignKey(Brand, null=True, on_delete=models.SET_NULL,
        related_name="product_brand")
    subcategory = models.ForeignKey(SubCategory, null=True, on_delete=models.SET_NULL,
        related_name="product_subcategory")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
        related_name="product_owner")
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL,
        through='Comment', related_name='product_comments')

    # Picture upload
    picture = models.BinaryField(null=True, blank=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, blank=True,
        help_text='The MimeTypeof the file')


    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        product_str = self.product
        if self.brand and self.subcategory:
            product_str = product_str + " by " + self.brand.brand + " (" + self.subcategory.category.category + ")"
        elif self.brand:
            product_str = product_str + " by " + self.brand.brand
        elif self.subcategory:
            product_str = product_str + " (" + self.subcategory.subcategory + ", " + self.subcategory.category.category + ")"
        return product_str


class Comment(models.Model):
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be longer than three characters")]
    )

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Like',
        related_name='liked_comments')
    likes_count = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Snippet
    def __str__(self):
        if len(self.text) < 17:
            return self.text
        return self.text[:13] + '...'


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='like_users')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('user', 'comment')

    def __str__(self):
        return '%s likes %s'%(self.user.username, self.comment.text[:9])


class Price(models.Model):
    advertised_price = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.01'))],
        help_text="The initial price you saw for the product"
    )
    shipping = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="Added cost for shipping."
    )
    hidden_fees = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="Fees added to the advertised price before checkout, except shipping."
    )
    higher_price_at_checkout = models.DecimalField(
        max_digits=8,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="The price charged at checkout, if it was higher. Leave 0.0 otherwise. Don't apply hidden fees."
    )
    overcharge = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="The overcharge price on your card, if higher than at checkout. Leave 0.0 otherwise. Don't apply hidden fees."
    )
    tied_sale = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="Add the price of other products you had to buy in order to get the product at advertised price."
        )
    total = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="Total cost of final product price and all fees."
        )
    tied_cost = models.DecimalField(
        max_digits=7,
        decimal_places=2,
        validators=[MinValueValidator(Decimal('0.00'))],
        default=0.0,
        help_text="Cost of buying all bundled products."
        )
    financing = models.BooleanField(default=False,
        help_text="Must buy financing to get product at advertised price.")
    subscription_fees = models.BooleanField(default=False,
        help_text="Price is conditional on subscription or subscription fees may apply.")
    phony_sale = models.BooleanField(default=False,
        help_text="The store lied about how much you saved on the product.")

    comments = models.CharField(max_length=128, blank=True,
        help_text="Describe any misleading pricing claims.")
    link = models.URLField(max_length=256)

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="price_product")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL,
        related_name="price_owner")

    date_observed = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        price_str = str(self.advertised_price) + " (on " + str(self.date_observed) + ")"
        return price_str


class Feature(models.Model):
    feature = models.CharField(max_length=128)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="feature_product")
    class Meta:
        unique_together = ['feature', 'product']

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return self.feature

cap/prcr/forms.py
from django import forms
from prcr.models import Feature, Product, Price, SubCategory
from django.core.files.uploadedfile import InMemoryUploadedFile
from prcr.humanize import naturalsize


class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=250, min_length=3, strip=True)


class FeatureCreateForm(forms.ModelForm):
    class Meta:
        model = Feature
        fields = ['feature']


class PriceForm(forms.ModelForm):
    class Meta:
        model = Price
        fields = [
            'advertised_price',
            'shipping',
            'hidden_fees',
            'higher_price_at_checkout',
            'overcharge',
            'tied_sale',
            'financing',
            'subscription_fees',
            'phony_sale',
            'comments',
            'link'
        ]


class SubcategoryCreateForm(forms.ModelForm):
    class Meta:
        model = SubCategory
        fields = ['subcategory']


class ProductBrandCreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Product
        fields = ['product', 'subcategory', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(ProductBrandCreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()

        return instance


class ProductSubcategoryCreateForm(ProductBrandCreateForm):
    class Meta:
        model = Product
        fields = ['product', 'brand', 'picture']


class ProductUpdateForm(ProductBrandCreateForm):
    class Meta:
        model = Product
        fields = ['product', 'brand', 'subcategory', 'picture']


class ProductAddImageForm(ProductBrandCreateForm):
    class Meta:
        model = Product
        fields = ['picture']


# Source: https://www.dj4e.com/lessons/dj4e_ads1b
# https://docs.djangoproject.com/en/4.2/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/4.2/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

cap/prcr/templates/prcr/brand_form.html
{% extends "base_form.html" %}


{% block page_header %}
<h2 class="display-5 text-dark">Add new brand</h2>
{% endblock page_header %}


{% block inner_content %}
<input type="submit" value="Cancel" class="btn btn-lg btn-outline-danger"
    onclick="window.location.href='{% url 'prcr:brand_list'%}';return false;">
{% endblock inner_content %}

cap/prcr/templates/prcr/brand_list.html
{% extends "base_menu.html" %}


{% block page_header %}
{% load humanize %}
<h2 class="display-5 text-dark">
    Browse<br>brands</h2>
<div>
    <p class="header-stat badge text-dark m-2 p-2 rounded-3 shadow">
        {% if search %} {% if filtered_list|length != 1 %} Your search found {{ filtered_list|length }} categories
        {% else %} Your search found 1 category {% endif %} {% else %}
        {% if brand_list|length != 1 %} {{ brand_list|length }} brands &nbsp;&raquo;&nbsp;
        {% else %} {{ brand_list|length }} brand &nbsp;&raquo;&nbsp; {% endif %}
        {% if product_list|length != 1 %} {{ product_list|length }} products</p>
        {% else %} {{ product_list|length }} product</p>{% endif %}{% endif %}
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form action="" method="get" class="m-2 input-group">
        <input type="text" name="search" class="form-control" list="brandList"
        {% if brand_list %}placeholder="Search for a brand name..."
        {% else %}placeholder="Nothing to search"{% endif %}>
        <datalist id="brandList">
            {% if brand_list %}{% for brand in brand_list %}
            <option value="{{ brand.brand }}"> {{ brand.brand }} </option>
            {% endfor %}{% endif %}
        </datalist>
        <button type="submit" class="btn btn-sm btn-success muted-link-style">
            <i class="fa fa-search p-2"></i></button>
        <a href="{% url 'prcr:main_list' %}" class="btn btn-sm btn-outline-dark link-style">
            <i class="fa fa-undo p-2"></i></a>
    </form>
</div>
<a class="header-link btn btn-md btn-outline-dark" href="{% url 'prcr:brand_create' %}">
    Add a brand<br> to Pricer &raquo;</a>
{% endblock page_header %}


{% block content %}
{% if filtered_list %}
{% for brand in filtered_list %}
<section class="container-fluid mt-3">
    <h4 class="heading p-3 mt-3 bg-light rounded-3 shadow text-dark d-flex justify-content-between align-items-center">
        {{ brand }}
        <a href="{% url 'prcr:product_brand_create' brand.id %}"
            class="btn btn-sm btn-outline-dark">
            Add {{ brand.brand }} products &raquo;</a>
    </h4>
</section>
<section class="container ">
    {% if product_list %}
    <div class="row m-0 container">
        {% for product in product_list %}
        {% if product.brand.id == brand.id %}
        <a href="{% url 'prcr:product_detail' product.id %}" class="link-style col-md-6">
            <div class="cards card p-2 mt-3 row g-0 border rounded-3 overflow-hidden shadow h-md-250 position-relative">

                <div class="row g-0 card-header flex-md-row">
                    <h5 class="link-style fs-3 text-dark pt-2">
                    {{ product.product }}
                    {% if product_lowest_price_list %}{% for product_id, total_price in product_lowest_price_list %}
                    {% if product_id == product.id %}
                    <span class="fs-6"> &#9679; best price ${{ total_price|intcomma }} </span></h5>
                    {% endif %}{% endfor %}{% endif %}
                    </div>
                <div class="card-body d-flex justify-content-between align-items-center">
                    <p class="card-text mb-auto text-muted text-small">
                        {% if feature_list %} <span class="text-muted"></span>
                        {% for feature in feature_list %}{% if feature.product.id == product.id %}
                        {{ feature }} &raquo;
                        {% endif %}{% endfor %}{% endif %}
                    </p>

                </div>
                {% if product.content_type %}
                    <img src="{% url 'prcr:product_picture' product.id %}" class="card-img-bottom card-pic">
                    {% endif %}
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    {% endif %}
</section>
{% endfor %}
{% elif brand_list|length == 0%}
<section class="section no-content p-3 m-3 bg-light rounded-3">
    <div class="text-danger p-3 m-3">
        <p class="fs-4">There are no categories yet in Pricer.<br>
            Add categories, subcategories and brands before creating a product.</p>
    </div>
</section>
{% elif filtered_list|length == 0%}
<section class="section no-content p-3 m-3 bg-light rounded-3">
    <div class="text-danger p-3 m-3">
        <p class="fs-4">There are no results for your search.</p>
    </div>
</section>
{% endif %}
{% endblock content %}


{% block footer %}
{% endblock footer %}

cap/prcr/templates/prcr/main_list.html
{% extends "base_menu.html" %}


{% block page_header %}
<h2 class="display-5 text-dark">
    Browse<br>categories</h2>
<div>
<p class="header-stat badge text-dark m-2 p-2 rounded-3 shadow">
    {% if search %} {% if filtered_list|length != 1 %} Your search found {{ filtered_list|length }} categories
    {% else %} Your search found 1 category {% endif %} {% else %}
    {% if category_list|length != 1 %} {{ category_list|length }} categories &nbsp;&raquo;&nbsp;
    {% else %} {{ category_list|length }} category &nbsp;&raquo;&nbsp; {% endif %}
    {% if subcategory_list|length != 1 %} {{ subcategory_list|length }} subcategories &nbsp;&raquo;&nbsp;
    {% else %} {{ subcategory_list|length }} subcategory &nbsp;&raquo;&nbsp; {% endif %}
    {% if product_list|length != 1 %} {{ product_list|length }} products<p>
    {% else %} {{ product_list|length }} product</p>{% endif %}{% endif %}
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form action="" method="get" class="m-2 input-group">
        <input type="text" name="search" class="form-control" list="categoryList"
        {% if category_list %}placeholder="Search for a category..."
        {% else %}placeholder="Nothing to search"{% endif %}>
        <datalist id="categoryList">
            {% if category_list %}{% for category in category_list %}
            <option value="{{ category.category }}"> {{ category.category }} </option>
            {% endfor %}{% endif %}
        </datalist>
        <button type="submit" class="btn btn-sm btn-success muted-link-style">
            <i class="fa fa-search p-2"></i></button>
        <a href="{% url 'prcr:main_list' %}" class="btn btn-sm btn-outline-dark link-style">
            <i class="fa fa-undo p-2"></i></a>
    </form>
</div>
<a class="header-link btn btn-md btn-outline-dark"
    href="{% url 'prcr:category_create' %}">
    Add a category<br>to Pricer &raquo;</a>
{% endblock page_header %}


{% block content %}
{% if filtered_list %}
{% for category in filtered_list %}
<section class="no-bg p-1 m-3 bg-light rounded-3">
    <div class="container-fluid">
        <h4 class="heading p-3 mb-3 bg-light rounded-3 shadow text-dark d-flex justify-content-between align-items-center">
        {{ category.category }}
        <button class="btn btn-sm btn-success" data-bs-toggle="collapse" data-bs-target="#{{ category.category }}-list"
            aria-expanded="false" aria-controls="{{ category.category }}-list">Show {{ category.category }} categories</button>
        <a href="{% url 'prcr:subcategory_create' category.id %}"
            class="btn btn-sm btn-outline-dark">
            Add a subcategory to {{ category.category|lower }} &raquo;</a></h4>
        {% if subcategory_list %}
        <ul id="{{ category.category }}-list" class="row collapse">
            {% for subcategory in subcategory_list %}
            {% if subcategory.category.id == category.id %}
            <li class="plain-list">
                <div class="cards p-3 mb-3 rounded 3 shadow text-small container">
                    <a href="{% url 'prcr:product_list' subcategory.id %}" class="link-style me-3">
                        <strong>{{ subcategory.subcategory }}</strong></a>
                    <button class="btn btn-sm btn-secondary" data-bs-toggle="collapse"
                        data-bs-target="#{{ category.category }}-{{ subcategory.subcategory }}-products"
                        aria-expanded="true"
                        aria-controls="{{ category.category }}-{{ subcategory.subcategory }}-products">
                        Hide {{ subcategory.subcategory }} list</button>
                    {% if product_list %}<span class="text-muted">
                    <ul class="row collapse show plain-list mt-2"
                        id="{{ category.category }}-{{ subcategory.subcategory }}-products">
                        {% for product in product_list %}
                        {% if product.subcategory.id == subcategory.id %}
                        <li class="m-1">
                            <a href="{% url 'prcr:product_detail' product.id %}" class="link-style">
                                &#9679; {{ product.product }}
                                <span class="text-muted">({{ product.brand.brand }})</span></a></li>
                        {% endif %}{% endfor %}</span>
                        </ul>
                        {% endif %}
                </div>
            </li>
            {% endif %}
            {% empty %}
            <p class="p-3 m-2 text-danger">This category has no subcategories. Add one.</p>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</section>
{% endfor %}
{% elif category_list|length == 0%}
<section class="section no-content p-3 m-3 bg-light rounded-3">
    <div class="text-danger p-3 m-3">
        <p class="fs-4">There are no categories yet in Pricer.<br>
            Add categories, subcategories and brands before creating a product.</p>
    </div>
</section>
{% elif filtered_list|length == 0%}
<section class="section no-content p-3 m-3 bg-light rounded-3">
    <div class="text-danger p-3 m-3">
        <p class="fs-4">There are no results for your search.</p>
    </div>
</section>
{% endif %}
{% endblock content %}


{% block footer %}
{% endblock footer %}

cap/prcr/templates/prcr/product_list.html
{% extends "base_menu.html" %}


{% block page_header %}
{% load humanize %}
<h2 class="text-dark"><span class="display-5"> {{ subcategory.subcategory }} </span><br>
    <span class="fs-5">&raquo; {{ subcategory.category }} </span></h2>
<div>
    <p class="header-stat badge text-dark m-2 p-2 rounded-3 shadow">
    {% if search and filtered_products == 1 %}
        {{ search }} found once in {{ subcategory.subcategory|lower }} {{ subcategory.category|lower }}
    {% elif search and filtered_products or search %}
        {{ search }} found {{ filtered_products|length }} times in {{ subcategory.subcategory|lower }} {{ subcategory.category|lower }}
    {% elif not search and filtered_products|length == 1 %}
        1 product in {{ subcategory.subcategory|lower }} {{ subcategory.category|lower }}
    {% elif not search and not filtered_products %}
        0 {{ subcategory.subcategory|lower }} {{ subcategory.category|lower }} in Pricer
    {% else %}
        {{filtered_products|length}} {{ subcategory.subcategory|lower }} {{ subcategory.category|lower }} in Pricer
    {% endif %}</p>
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form  class="m-2 input-group">
        <input type="text" name="search" placeholder="Search product names..." class="form-control"
            {% if search %} value="{{ search }}" {% endif %}>
        <button type="submit" class="btn btn-sm btn-success muted-link-style">
            <i class="fa fa-search p-2"></i></button>
        <a href="{% url 'prcr:product_list' subcategory.id %}"
            class="btn btn-sm btn-outline-dark link-style"><i class="fa fa-undo p-2"></i></a>
    </form>
</div>
<p><a class="btn btn-md btn-outline-dark mt-3 ms-2"
    href="{% url 'prcr:product_subcategory_create' subcategory.id %}">
    Add a new product<br>to {{ subcategory|lower }} &raquo;</a></p>
{% endblock page_header %}


{% block content %}
{% for product in filtered_products %}
<section class="product p-2 pt-3 m-3 bg-light rounded-3 shadow">
    <div class="container-fluid d-flex justify-content-between">
        <div><a href="{% url 'prcr:product_detail' product.id %}"
            class="link-style text-start fs-3 btn">
            <span class="fs-3"> {{ product.product }} </span>
            {% for brand in brands %}{% if brand.id == product.brand_id %}
            <span class="fs-6">({{ brand.brand }})
            {% endif %}{% endfor %}
            {% if product_lowest_price_list %}{% for product_id, total_price in product_lowest_price_list %}
            {% if product_id == product.id %}
            &#9679; Lowest price offer ${{ total_price|intcomma }}
            {% endif %}{% endfor %}{% endif %}<br>
            {% if feature_list %}{% for feature in feature_list %}{% if feature.product_id == product.id %}
            {{ feature }} &raquo; {% endif %}{% endfor %}{% endif %}</span></a>
            {% if comments %}{% for comment in comments %}{% if forloop.counter == 1 %}{% if comment.product.id == product.id %}
            <p class="text-success ps-3">Popular product</p>
            {% endif %}{% endif %}{% endfor %}{% endif %}
            {% if product.owner_id == user.id %}
            <p><a class="btn btn-sm btn-outline-secondary m-3"
                href="{% url 'prcr:product_update' product.id %}">
                Edit this product &raquo;</a></p>
            {% endif %}
        </div>
        {% if product.content_type %}
        <img class="product-pic rounded-3 m-1"
            src="{% url 'prcr:product_picture' product.id %}">
        {% else %}
        <a href="{% url 'prcr:product_add_image' product.id %}"
            class="product-no-pic link-style outline-secondary rounded-3 m-1">
            Add<br>an<br>image</a>
        {% endif %}
    </div>
</section>
{% endfor %}
{% if search and not filtered_products %}
<section class="section no-content p-3 m-3 bg-light rounded-3">
    <div class="text-danger p-3 m-3">
        <p class="fs-4">There are no results for your search.</p>
    </div>
</section>
{% elif not search and not filtered_products %}
<section class="section no-content p-3 m-3 bg-light rounded-3">
    <div class="text-danger p-3 m-3">
        <p class="fs-4">There are no {{ subcategory|lower }} {{ subcategory.category|lower }} yet.<br>You may add one.</p>
    </div>
</section>
{% endif %}
{% endblock content %}


{% block footer %}
{% endblock footer %}